<?php 

$page = "partner";
include_once 'inc/required/head.php';?>


                    
        </div>
    </nav>

    <style>
    h1.text-center.aos-init.aos-animate {
    color: white;
}
</style>

<br><br><br><br><br><br>

<section id="partners">
        <h1 class="text-left" style="color: rgba(221,27,61,1.00);font-size: x-large; margin: 0px 17px; text-align:center;"><!--PARTNERS--><br></h1>
        <div>
            <div class="container">
                <div class="row">
                    <div class="col-md-12"><h1 id="partners" style="text-align:center">BECOME A PARTNER AND JOIN OUR NETWORK<br/></h1>
                        <p id="partners" style="text-align:center">We forward our leads with the information required, enabling our partners to quote.<br/></p>
                        <br><br>
                            <?php include_once 'carousel.php';?>
                        <br><br>


                        <h1 class="text-left" style="color: rgba(221,27,61,1.00);font-size: x-large; margin: 0px 17px;"></h1>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <br><br><br><br>

    





    <section id="services">
        <!-- <h1 class="text-left" style="color: rgba(221,27,61,1.00);font-size: x-large;margin:0px 17px; text-align:center;">SERVICES<br></h1>-->
        <div class="card" style="margin-bottom:20px;"></div>
        <div class="card-body">         
            <center><h1 style="color:rgba(191,56,56);font-size:xx-large;font-weight:900;margin:0px 17px;text-align:center;">Become a Partner / Service Provider<br></h1></center>
            <br>
            <div class="row">
                <div class="col-1">
                </div>
                <div class="col-4">
                    <ul>
                        <li>	100% Free Registration</li>
                        <li>	14 Day Free Trial</li>
                        <li>	Excellent Support</li>
                        <li>	No Long-Term Commitments</li>
                        <li>	No Additional Costs</li>
                        <li>	Trial ends automatically</li>
                        <li>	No notice periods</li>
                        <li>	Cancel online anytime, no contract</li>
                        <li>	Information is confidential</li>
                    </ul>   
                </div>
                <div class="col-6">
                <b>WHY USE RELOCATION STATION:</b>
                    <p>The main reason to subscribe to Relocation Station is that as a partner you will only compete against industry leaders, there will be no fly  by night companies or bakkie to hire companies, there will be no new start-up removal companies that under quote and then push the price up once they have the furniture on the truck.</p> 
                    <p>As a company you will be able to work with a flat rate per month that can be calculated into your advertising budget, we will be doing the AdWords and SEO for the website and out of that you will get every lead generated by the site, and you can decide if you want to quote or not.</p>

                </div>
            </div>
            <br><br>
            <div class="row">
                <div class="col-1">
                </div>
                <div class="col-4">
                <b>HOW IT WORKS:</b>

                    <ul>
                        <!-- <li>	<s>Manage your profile anytime – You are in full control</s></li> -->
                        <li>	Project Request – New Customers</li>
                        <li>	Build Your Companies Reputation</li>
                        <li>	Get more exposure</li>
                        <li>	We will add your logo to our website</li>
                        <!-- <li>	<s>Get Reviews</s></li> -->
                    </ul>   
                </div>
                
                <div class="col-2">
                </div>
                <div class="col-2">
                    <div class="clear-fix"><br><br><br>
                    <a href="partnerSignup.php"><button type="submint" class="btn btn-primary">Signup Now!</button></a>
                    </div>
               

                </div>
            </div>
    </section>


    <section>
        <div class="row">
            <div class="col">
                <div class="parallax">
                    <div class="card" id="paraCard">
                        <div class="card-body">
                            <h4 class="card-title" style="  color: white; text-align: center; padding-top: 50px;">If you can fulfil a position in our network</h4>
                            <h1 style="  font-size: 46px; color: white; text-align: center;">Signup<br /> and start <br /> moving people.</h1>
                            <p style="  text-align: center; color: white;"><br /><br />
                                <a href="partnerSignup.php"><button class="btn btn-primary" type="button">Signup Now</button></a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>





    <?php include_once 'inc/required/footer.php';
    
    unset($page);

    ?>